services:
  postgres:
    container_name: skill_board_postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: skill_board_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: skill_board_seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: "admin"
      SEQ_FIRSTRUN_ADMINPASSWORD: "YourStrong!Pass1"
    ports:
      - "8082:80"    # UI Ð¸ API
      - "5432:5341"  # Ingestion endpoint
    volumes:
      - seq-data:/data

volumes:
  postgres-data:
  seq-data:
